=== OliverRose33/Pokemon-CLI/pokemon-cli/appdata/schema/move.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Move",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "move_id": {
                "type": "integer"
            },
            "name": {
                "type": "string"
            },
            "type": {
                "type": "string"
            },
            "category": {
                "$ref": "#/$defs/category"
            },
            "description": {
                "type": "string"
            },
            "max_pp": {
                "type": "integer",
                "exclusiveMinimum": 0
            },
            "power": {
                "type": "integer",
                "minimum": 0
            },
            "accuracy": {
                "$ref": "#/$defs/percentage"
            }
        },
        "required": [
            "move_id",
            "name",
            "type",
            "category",
            "description",
            "power",
            "max_pp"
        ]
    },
    "$defs": {
        "category": {
            "enum": [
                "physical",
                "special",
                "status"
            ]
        },
        "percentage": {
            "type": "integer",
            "exclusiveMinimum": 0,
            "maximum": 100
        }
    }
}

=== OliverRose33/Pokemon-CLI/pokemon-cli/appdata/moves.json
[
    {
        "move_id": 1,
        "name": "Pound",
        "type": "normal",
        "category": "physical",
        "description": "The target is physically pounded with a long tail, a foreleg, or the like.",
        "max_pp": 35,
        "power": 40,
        "accuracy": 100
    },
    {
        "move_id": 2,
        "name": "Karate Chop",
        "type": "fighting",
        "category": "physical",
        "description": "The target is attacked with a sharp chop. Critical hits land more easily.",
        "max_pp": 25,
        "power": 50,
        "accuracy": 100
    }
]
